"""Tests for tools/validate_decks.py."""
import os
import json
import pytest
from tools.validate_decks import (
    validate, write_reports,
    _normalize_lines, _sha256_lines,
    _classify_hunk, _level3_classify,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(content)


NOMINAL_A = """\
* SPICE deck for DFFQ1
.inc '/abs/path/to/model.spi'
.param vdd=0.450
.param seed=12345
.param monte=500
sweep monte 200
.tran 1p 10n
.end
"""

NOMINAL_B = """\
* SPICE deck for DFFQ1
.inc '/different/abs/path/model.spi'
.param vdd=0.450
.param seed=99999
.param monte=1
sweep monte 1
.tran 1p 10n
.end
"""

NOMINAL_DIFFERENT = """\
* SPICE deck for DFFQ1
.inc '/abs/path/to/model.spi'
.param vdd=0.900
.param seed=1
.param monte=1
sweep monte 1
.tran 2p 20n
.end
"""


# ---------------------------------------------------------------------------
# Level 1: byte-identical
# ---------------------------------------------------------------------------

class TestLevel1:
    def test_identical_files(self, tmp_path):
        arc_id = 'hold_CELL_Q_rise_CP_rise_NO_CONDITION_1_1'
        for side in ('dg', 'mq'):
            p = tmp_path / side / 'hold' / arc_id
            make_file(str(p / 'nominal_sim.sp'), NOMINAL_A)

        report = validate(
            deckgen_root=str(tmp_path / 'dg' / 'hold'),
            mcqc_root=str(tmp_path / 'mq' / 'hold'),
            filename='nominal_sim.sp',
            arc_types=[''],
        )
        # arc_type '' maps to root -- use flat structure instead
        # Re-test with explicit arc_type dir

    def test_byte_identical_level1(self, tmp_path):
        arc_id = 'hold_CELL_Q_rise_CP_rise_NO_CONDITION_1_1'
        dg_dir = tmp_path / 'dg' / 'hold' / arc_id
        mq_dir = tmp_path / 'mq' / 'hold' / arc_id
        make_file(str(dg_dir / 'nominal_sim.sp'), NOMINAL_A)
        make_file(str(mq_dir / 'nominal_sim.sp'), NOMINAL_A)

        report = validate(
            deckgen_root=str(tmp_path / 'dg'),
            mcqc_root=str(tmp_path / 'mq'),
            filename='nominal_sim.sp',
        )
        at = report['arc_types']['hold']
        assert at['level1_identical'] == 1
        assert at['level2_identical'] == 0
        assert at['level3_only_diffs'] == 0
        assert report['summary']['identical'] == 1
        assert report['summary']['different'] == 0


# ---------------------------------------------------------------------------
# Level 2: noise normalization
# ---------------------------------------------------------------------------

class TestLevel2:
    def test_normalize_paths(self):
        lines = [".inc '/abs/path/model.spi'\n"]
        norm = _normalize_lines(lines)
        assert norm == [".inc 'model.spi'"]

    def test_normalize_seed(self):
        lines = [".param seed=99999\n"]
        norm = _normalize_lines(lines)
        assert norm == [".param seed=1"]

    def test_normalize_monte(self):
        lines = [".param monte=500\n"]
        norm = _normalize_lines(lines)
        assert norm == [".param monte=1"]

    def test_normalize_sweep(self):
        lines = ["sweep monte 200\n"]
        norm = _normalize_lines(lines)
        assert norm == ["sweep monte 1"]

    def test_normalize_strips_comment(self):
        lines = ["* Generated by deckgen\n", ".param vdd=0.45\n"]
        norm = _normalize_lines(lines)
        assert ".param vdd=0.45" in norm
        assert not any("Generated" in l for l in norm)

    def test_normalize_strips_trailing_blank(self):
        lines = ["a\n", "\n", "\n"]
        norm = _normalize_lines(lines)
        assert norm == ["a"]

    def test_level2_identical(self, tmp_path):
        """Files differing only in abs paths / seeds are Level 2 identical."""
        arc_id = 'delay_CELL_Z_rise_A1_fall_NO_CONDITION_1_1'
        dg_dir = tmp_path / 'dg' / 'delay' / arc_id
        mq_dir = tmp_path / 'mq' / 'delay' / arc_id
        make_file(str(dg_dir / 'nominal_sim.sp'), NOMINAL_A)
        make_file(str(mq_dir / 'nominal_sim.sp'), NOMINAL_B)

        report = validate(
            deckgen_root=str(tmp_path / 'dg'),
            mcqc_root=str(tmp_path / 'mq'),
            filename='nominal_sim.sp',
        )
        at = report['arc_types']['delay']
        assert at['level1_identical'] == 0
        assert at['level2_identical'] == 1
        assert at['level3_only_diffs'] == 0


# ---------------------------------------------------------------------------
# Level 3: line class classification
# ---------------------------------------------------------------------------

class TestLevel3:
    def test_classify_path(self):
        a = [".inc '/path/a/model.spi'"]
        b = [".inc '/path/b/model.spi'"]
        assert _classify_hunk(a, b) == 'path'

    def test_classify_numeric(self):
        a = [".param vdd=0.450"]
        b = [".param vdd=0.900"]
        assert _classify_hunk(a, b) == 'value_numeric'

    def test_classify_extra(self):
        assert _classify_hunk([], [".extra line"]) == 'extra'

    def test_classify_missing(self):
        assert _classify_hunk([".missing line"], []) == 'missing'

    def test_classify_comment(self):
        a = ["* comment A"]
        b = ["* comment B"]
        assert _classify_hunk(a, b) == 'comment'

    def test_classify_other(self):
        a = [".tran 1p 10n"]
        b = [".dc sweep 0 1"]
        assert _classify_hunk(a, b) == 'other'

    def test_level3_diff_detected(self, tmp_path):
        """Files with real content differences -> Level 3."""
        arc_id = 'hold_CELL2_Q_rise_CP_rise_NO_CONDITION_1_1'
        dg_dir = tmp_path / 'dg' / 'hold' / arc_id
        mq_dir = tmp_path / 'mq' / 'hold' / arc_id
        make_file(str(dg_dir / 'nominal_sim.sp'), NOMINAL_A)
        make_file(str(mq_dir / 'nominal_sim.sp'), NOMINAL_DIFFERENT)

        report = validate(
            deckgen_root=str(tmp_path / 'dg'),
            mcqc_root=str(tmp_path / 'mq'),
            filename='nominal_sim.sp',
        )
        at = report['arc_types']['hold']
        assert at['level3_only_diffs'] == 1
        assert at['level1_identical'] == 0
        assert at['level2_identical'] == 0
        assert report['summary']['different'] == 1


# ---------------------------------------------------------------------------
# Pairing and orphans
# ---------------------------------------------------------------------------

class TestPairing:
    def test_orphan_deckgen_only(self, tmp_path):
        """Arc in deckgen but not mcqc -> orphan_deckgen."""
        arc_id = 'hold_ORPHAN_Q_rise_CP_rise_NO_CONDITION_1_1'
        dg_dir = tmp_path / 'dg' / 'hold' / arc_id
        make_file(str(dg_dir / 'nominal_sim.sp'), NOMINAL_A)

        report = validate(
            deckgen_root=str(tmp_path / 'dg'),
            mcqc_root=str(tmp_path / 'mq'),
            filename='nominal_sim.sp',
        )
        at = report['arc_types']['hold']
        assert arc_id in at['orphans_deckgen']
        assert at['total_pairs'] == 0

    def test_orphan_mcqc_only(self, tmp_path):
        """Arc in mcqc but not deckgen -> orphan_mcqc."""
        arc_id = 'hold_ORPHAN2_Q_rise_CP_rise_NO_CONDITION_1_1'
        mq_dir = tmp_path / 'mq' / 'hold' / arc_id
        make_file(str(mq_dir / 'nominal_sim.sp'), NOMINAL_A)

        report = validate(
            deckgen_root=str(tmp_path / 'dg'),
            mcqc_root=str(tmp_path / 'mq'),
            filename='nominal_sim.sp',
        )
        at = report['arc_types']['hold']
        assert arc_id in at['orphans_mcqc']

    def test_mixed_pairs_and_orphans(self, tmp_path):
        """2 matched, 1 orphan each side."""
        for i in range(2):
            arc_id = f'hold_CELL{i}_Q_rise_CP_rise_NO_CONDITION_1_1'
            for side in ('dg', 'mq'):
                d = tmp_path / side / 'hold' / arc_id
                make_file(str(d / 'nominal_sim.sp'), NOMINAL_A)

        dg_only = tmp_path / 'dg' / 'hold' / 'hold_DGONLY_Q_rise_CP_rise_NO_CONDITION_1_1'
        mq_only = tmp_path / 'mq' / 'hold' / 'hold_MQONLY_Q_rise_CP_rise_NO_CONDITION_1_1'
        make_file(str(dg_only / 'nominal_sim.sp'), NOMINAL_A)
        make_file(str(mq_only / 'nominal_sim.sp'), NOMINAL_A)

        report = validate(
            deckgen_root=str(tmp_path / 'dg'),
            mcqc_root=str(tmp_path / 'mq'),
            filename='nominal_sim.sp',
        )
        at = report['arc_types']['hold']
        assert at['total_pairs'] == 2
        assert at['level1_identical'] == 2
        assert len(at['orphans_deckgen']) >= 1
        assert len(at['orphans_mcqc']) >= 1


# ---------------------------------------------------------------------------
# Output files
# ---------------------------------------------------------------------------

class TestWriteReports:
    def test_json_and_html_written(self, tmp_path):
        arc_id = 'hold_CELL_Q_rise_CP_rise_NO_CONDITION_1_1'
        for side in ('dg', 'mq'):
            d = tmp_path / side / 'hold' / arc_id
            make_file(str(d / 'nominal_sim.sp'), NOMINAL_A)

        report = validate(
            deckgen_root=str(tmp_path / 'dg'),
            mcqc_root=str(tmp_path / 'mq'),
            filename='nominal_sim.sp',
        )
        out = tmp_path / 'reports'
        json_path, html_path = write_reports(report, str(out))
        assert os.path.isfile(json_path)
        assert os.path.isfile(html_path)

        with open(json_path) as f:
            loaded = json.load(f)
        assert loaded['summary']['total'] == 1

        with open(html_path, encoding='ascii') as f:
            html = f.read()
        assert 'DeckGen vs MCQC' in html
        # ASCII-only check: no bytes above 127
        assert all(ord(c) < 128 for c in html)
