"""
deck_builder.py - Builds SPICE decks from templates and resolved parameters.

Handles:
  - Template variable substitution ($VAR -> value)
  - When-condition pin waveform generation
  - Arc-type-specific measurement setup (delay/slew/hold)
  - Output load insertion
  - Voltage source generation
"""

import os
import re
import yaml


# Arc type -> timing parameter profile
# Hold uses more timing points (multi-stage synchronizers)
# Delay/slew use fewer
TIMING_PROFILES = {
    'delay': {
        'waveform_model_rise': 'stdvs_rise',
        'waveform_model_fall': 'stdvs_fall',
        'timing_params': ['t01', 't02', 't03'],
        'nodeset_latch_internals': False,
    },
    'slew': {
        'waveform_model_rise': 'stdvs_rise',
        'waveform_model_fall': 'stdvs_fall',
        'timing_params': ['t01', 't02', 't03'],
        'nodeset_latch_internals': False,
    },
    'hold': {
        'waveform_model_rise': 'stdvs_mpw_fall_rise_fall_rise_fall_rise_fall',
        'waveform_model_fall': 'stdvs_mpw_rise_fall_rise_fall_rise_fall_rise',
        'timing_params': ['t01', 't02', 't03', 't04', 't05', 't06', 't07'],
        'nodeset_latch_internals': True,
    },
}


def build_deck(arc_info, global_config=None, slew=None, load=None,
               when=None, max_slew=None):
    """Build a SPICE deck from a resolved arc_info dict.

    Args:
        arc_info: dict from resolver.resolve_all()
        global_config: parsed config.yaml dict (optional)
        slew: tuple (constr_pin_slew, rel_pin_slew) with units, e.g. ("2.5n", "1.2n")
        load: output load with units, e.g. "0.5f"
        when: when condition string, e.g. "!SE&SI" or "NO_CONDITION"
        max_slew: max slew with units, e.g. "2.5n"

    Returns:
        list[str]: SPICE deck lines ready to write
    """
    template_path = arc_info['TEMPLATE_DECK_PATH']
    arc_type = arc_info['ARC_TYPE']

    with open(template_path, 'r') as f:
        template_lines = f.readlines()

    # Build substitution map
    sub_map = _build_substitution_map(arc_info, slew, load, max_slew)

    # Get timing profile for this arc type
    profile = TIMING_PROFILES.get(arc_type, TIMING_PROFILES['delay'])

    # Process template line by line
    write_list = []
    for line in template_lines:
        processed = _process_line(line, sub_map, arc_info, profile, when)
        if isinstance(processed, list):
            write_list.extend(processed)
        else:
            write_list.append(processed)

    return write_list


def _build_substitution_map(arc_info, slew, load, max_slew):
    """Build the $VAR -> value substitution map."""
    constr_slew = slew[0] if slew else '0'
    rel_slew = slew[1] if slew else '0'
    output_load = load or '0'

    # Header info
    header = (
        f"* Cell: {arc_info['CELL_NAME']}\n"
        f"* Arc Type: {arc_info['ARC_TYPE']}\n"
        f"* Related Pin: {arc_info['REL_PIN']} ({arc_info['REL_PIN_DIR']})\n"
        f"* Constrained Pin: {arc_info['CONSTR_PIN']} ({arc_info.get('CONSTR_PIN_DIR', '')})\n"
        f"* Probe Pin: {arc_info.get('PROBE_PIN_1', '')}\n"
        f"* Generated by deckgen"
    )

    sub = {
        'HEADER_INFO': arc_info.get('HEADER_INFO', header),
        'CELL_NAME': arc_info['CELL_NAME'],
        'REL_PIN': arc_info['REL_PIN'],
        'CONSTR_PIN': arc_info['CONSTR_PIN'],
        'PROBE_PIN_1': arc_info.get('PROBE_PIN_1', ''),
        'NETLIST_PINS': arc_info.get('NETLIST_PINS', ''),
        'NETLIST_PATH': arc_info.get('NETLIST_PATH', ''),
        'WAVEFORM_FILE': arc_info.get('WAVEFORM_FILE', ''),
        'INCLUDE_FILE': arc_info.get('INCLUDE_FILE', ''),
        'VDD_VALUE': arc_info.get('VDD_VALUE', ''),
        'TEMPERATURE': arc_info.get('TEMPERATURE', ''),
        'OUTPUT_LOAD': arc_info.get('OUTPUT_LOAD', output_load) or output_load,
        'INDEX_1_VALUE': arc_info.get('INDEX_1_VALUE', constr_slew) or constr_slew,
        'INDEX_2_VALUE': arc_info.get('INDEX_2_VALUE', rel_slew) or rel_slew,
        'MAX_SLEW': arc_info.get('MAX_SLEW', '') or max_slew or rel_slew or '1n',
        'PUSHOUT_PER': arc_info.get('PUSHOUT_PER', '0.4'),
        # MCQC-parity substitutions (Point 2a)
        'WHEN':             arc_info.get('WHEN', ''),
        'LIT_WHEN':         arc_info.get('LIT_WHEN', ''),
        'VECTOR':           arc_info.get('VECTOR', ''),
        'SIDE_PIN_STATES':  arc_info.get('SIDE_PIN_STATES', ''),
        'DONT_TOUCH_PINS':  arc_info.get('DONT_TOUCH_PINS', ''),
        'OUTPUT_PINS':      arc_info.get('OUTPUT_PINS', ''),
        'TEMPLATE_PINLIST': arc_info.get('TEMPLATE_PINLIST', ''),
        'INDEX_1_INDEX':    arc_info.get('INDEX_1_INDEX', ''),
        'INDEX_2_INDEX':    arc_info.get('INDEX_2_INDEX', ''),
        'INDEX_3_INDEX':    arc_info.get('INDEX_3_INDEX', ''),
        'GLITCH':           arc_info.get('GLITCH', ''),
        'PUSHOUT_DIR':      arc_info.get('PUSHOUT_DIR', ''),
        'TEMPLATE_DECK':    arc_info.get('TEMPLATE_DECK', ''),
        'TEMPLATE_TCL':     arc_info.get('TEMPLATE_TCL', ''),
    }
    return sub


def _process_line(line, sub_map, arc_info, profile, when):
    """Process a single template line, returning one or more output lines."""

    # Section: Pin definitions -- inject when-condition pin settings
    if '* Pin definitions' in line:
        result = [line]
        result.extend(_generate_when_condition_lines(arc_info, when))
        return result

    # Section: Output Load -- inject load capacitor line
    if '* Output Load' in line:
        result = [line]
        load_val = sub_map.get('OUTPUT_LOAD', '0')
        if load_val and load_val != '0':
            probe = arc_info.get('PROBE_PIN_1', 'Y')
            result.append(f"CL {probe} 0 'cl'\n")
        return result

    # Section: Voltage -- inject extra power pins if needed
    if '* Voltage' in line:
        return [line]

    # Variable substitution for lines with $
    if '$' in line:
        return _substitute_vars(line, sub_map)

    return line


def _substitute_vars(line, sub_map):
    """Replace $VARIABLE_NAME with values from sub_map."""
    result = line
    # Find all $WORD patterns
    for match in re.findall(r'\$([A-Z_][A-Z_0-9]*)', line):
        if match in sub_map:
            result = result.replace(f'${match}', str(sub_map[match]))
    return result


def _generate_when_condition_lines(arc_info, when):
    """Generate pin voltage source lines for when conditions.

    When condition format: "!SE&SI&D" means SE=0, SI=1, D=1
    "NO_CONDITION" or None means no when pins.
    """
    lines = []

    if not when or when == 'NO_CONDITION':
        return lines

    vdd = arc_info.get('VDD_VALUE', '0.5')
    conditions = when.split('&')

    for cond in conditions:
        cond = cond.strip()
        if not cond:
            continue

        # Skip the constrained/related pins -- they're already driven
        pin_name = cond.lstrip('!')
        if pin_name == arc_info['REL_PIN'] or pin_name == arc_info['CONSTR_PIN']:
            continue

        # Determine voltage: ! prefix means LOW, otherwise HIGH
        if cond.startswith('!'):
            voltage = '0'
        else:
            voltage = f"'{vdd}'"

        lines.append(f"V{pin_name} {pin_name} 0 {voltage}\n")

    return lines


def build_mc_deck(nominal_lines, num_samples=5000):
    """Convert a nominal deck to a Monte Carlo sweep deck.

    Modifies the .tran line to add sweep monte=N.

    Args:
        nominal_lines: list of SPICE deck lines (from build_deck)
        num_samples: number of MC samples

    Returns:
        list[str]: MC deck lines
    """
    mc_lines = []
    for line in nominal_lines:
        if '.tran' in line.lower() and '.end' not in line.lower():
            # Replace existing monte= or append it
            if 'monte=' in line:
                line = re.sub(r'monte=\d+', f'monte={num_samples}', line)
            elif 'sweep' in line:
                line = line.rstrip() + f' monte={num_samples}\n'
            else:
                # Insert sweep monte before the end of the line
                line = line.rstrip() + f' sweep monte={num_samples}\n'
        mc_lines.append(line)
    return mc_lines
