"""
Stage 4 -- Deck generation (spec SS5).
  in : DeviceGraph + Arc + Sensitization + Initialization + measurement + model
  out: Deck (golden-structured)

The deck is laid out like the incumbent golden deck so it can be diffed by eye.
It is split into clearly-labeled sections:
  - COLLATERAL: supplied by the flow (includes, corner, .tran). In direct mode
    these are placeholders; on the server they are the real paths.
  - ENGINE-DERIVED: the X1 instance, the P1-proven sensitization biases, the
    drive-and-settle initialization, and the P2 probes -- this is what the engine
    owns and what should be compared against the golden deck.
  - MEASUREMENT: Liberate's block, passed through UNCHANGED.
"""
from __future__ import annotations

from engine.types import (
    Arc,
    Deck,
    DeviceGraph,
    InitializationResult,
    SensitizationResult,
)

STAGE = "S4.deck"


def _railref(value) -> str:
    return "vdd_value" if value == 1 else "vss_value"


def assemble(
    graph: DeviceGraph,
    arc: Arc,
    sens: SensitizationResult,
    init: InitializationResult,
    measurement_block: str,
    model_text: str,
) -> Deck:
    sections: dict[str, str] = {}

    sections["header"] = (
        "** SPICE Deck generated by DeckGen v2 **\n"
        f"* CELL {arc.cell} | REL_PIN {arc.rel_pin} | REL_PIN_DIR {arc.rel_dir} "
        f"| CONSTR_PIN {arc.constr_pin} | CONSTR_PIN_DIR {arc.constr_dir} "
        f"| ARC_TYPE {arc.arc_type} | WHEN {arc.when or 'NO_CONDITION'}"
    )

    sections["collateral"] = "\n".join([
        "* ===== COLLATERAL (supplied by flow; placeholders in direct mode) =====",
        ".inc 'std_wv.spi'                 $ COLLATERAL waveform lib",
        ".inc 'MODEL.hold.inc'             $ COLLATERAL device models (corner)",
        f".inc '{arc.cell}.spi'             $ COLLATERAL LPE netlist",
        ".param vdd_value = '0.450'        $ COLLATERAL corner voltage",
        ".param vss_value = 0",
        ".temp -40                         $ COLLATERAL corner temp",
        ".param cl = '0.000542p'           $ COLLATERAL output load",
        "VVDD VDD 0 'vdd_value'",
        "VVSS VSS 0 'vss_value'",
        "VVPP VPP 0 'vdd_value'",
        "VVBB VBB 0 'vss_value'",
        "CQ Q 0 'cl'",
    ])

    biases = []
    for pin, d in sens.side_biases.items():
        role = "select" if pin in sens.set_pins else "masked"
        biases.append(f"V{pin} {pin} 0 '{_railref(d.value)}'   "
                      f"$ derived {pin}={d.value} ({role})")
    sections["engine"] = "\n".join(
        ["* ===== ENGINE-DERIVED ====="]
        + [f"X1 {' '.join(graph.ports)} {arc.cell}"]
        + [f"* sensitization (P1 {'PROVEN' if sens.proven else 'NOT PROVEN'}):"]
        + biases
        + ["* initialization (drive-and-settle, derived):"]
        + init.stimulus
        + ["* P2 probes (structural storage nodes):"]
        + [f".probe v({node})" for node in init.probes]
    )

    sections["measurement"] = "\n".join([
        "* ===== MEASUREMENT (Liberate, passed through UNCHANGED) =====",
        measurement_block.rstrip("\n"),
        ".tran 1p 5000n sweep monte=1     $ COLLATERAL",
    ])

    text = "\n".join([
        sections["header"], "",
        sections["collateral"], "",
        sections["engine"], "",
        sections["measurement"],
        ".end",
    ]) + "\n"
    return Deck(cell=arc.cell, text=text, sections=sections)
