"""
_gen_sdf_lpe.py -- deterministic generator for the THROWAWAY LPE scan-DFF fixture.

This emits an LPE-style netlist that is FORMAT-FAITHFUL to the real one
(per SEGMENT 2 photos): macro-subckt transistors `X<name> d g s b nch/pch_svt_mac`
whose terminals are private extracted nodes (`X<name>#d`), with all logical
connectivity carried by parasitic `R` (and some noise `C` the engine must ignore).
It is the GENERATOR that documents the intended synthetic topology; the engine
must re-derive that topology blind, by R-merging and CCC -- never by these names.

No PDK. Generic models only. Run:  python3 engine/fixtures/_gen_sdf_lpe.py
"""
from __future__ import annotations

CELL = "SDFX_LPE_PLACEHOLDER"
PORTS = ["SI", "D", "SE", "CP", "Q", "VDD", "VSS", "VPP", "VBB"]
RAILS = {"VDD", "VSS", "VPP", "VBB"}

# (name, kind, d_net, g_net, s_net, b_net) -- LOGICAL nets (pre-extraction).
# Topology: clock inv -> scan mux (SE) -> master latch -> slave latch -> out inv.
DEVICES = [
    # clock inverter: clkb = NOT CP
    ("XCKA0", "pmos", "clkb", "CP", "VDD", "VPP"),
    ("XCKA1", "nmos", "clkb", "CP", "VSS", "VBB"),
    # scan-enable inverter: seb = NOT SE
    ("XSEA0", "pmos", "seb", "SE", "VDD", "VPP"),
    ("XSEA1", "nmos", "seb", "SE", "VSS", "VBB"),
    # scan mux into mi: pass D when SE=0, pass SI when SE=1
    ("XMSA0", "nmos", "mi", "seb", "D", "VBB"),
    ("XMSA1", "pmos", "mi", "SE", "D", "VPP"),
    ("XMSA2", "nmos", "mi", "SE", "SI", "VBB"),
    ("XMSA3", "pmos", "mi", "seb", "SI", "VPP"),
    # master write TG: mi -> ml_a, transparent when CP=0 (clkb=1)
    ("XMSA4", "nmos", "ml_a", "clkb", "mi", "VBB"),
    ("XMSA5", "pmos", "ml_a", "CP", "mi", "VPP"),
    # master inverter: ml_b = NOT ml_a
    ("XMLA0", "pmos", "ml_b", "ml_a", "VDD", "VPP"),
    ("XMLA1", "nmos", "ml_b", "ml_a", "VSS", "VBB"),
    # master feedback inverter: ml_a = NOT ml_b  (cross-couple -> storage bit)
    ("XMFA0", "pmos", "ml_a", "ml_b", "VDD", "VPP"),
    ("XMFA1", "nmos", "ml_a", "ml_b", "VSS", "VBB"),
    # slave write TG: ml_b -> sl_a, transparent when CP=1
    ("XSSA0", "nmos", "sl_a", "CP", "ml_b", "VBB"),
    ("XSSA1", "pmos", "sl_a", "clkb", "ml_b", "VPP"),
    # slave inverter: sl_b = NOT sl_a
    ("XSLA0", "pmos", "sl_b", "sl_a", "VDD", "VPP"),
    ("XSLA1", "nmos", "sl_b", "sl_a", "VSS", "VBB"),
    # slave feedback inverter: sl_a = NOT sl_b  (cross-couple -> storage bit)
    ("XSFA0", "pmos", "sl_a", "sl_b", "VDD", "VPP"),
    ("XSFA1", "nmos", "sl_a", "sl_b", "VSS", "VBB"),
    # output inverter: Q = NOT sl_a
    ("XOUT0", "pmos", "Q", "sl_a", "VDD", "VPP"),
    ("XOUT1", "nmos", "Q", "sl_a", "VSS", "VBB"),
]

MODEL = {"nmos": "nch_svt_mac", "pmos": "pch_svt_mac"}


def build():
    # Collect, per logical net, the list of private device-pin nodes attached.
    pins_by_net: dict[str, list[str]] = {}
    dev_lines: list[str] = []
    for name, kind, d, g, s, b in DEVICES:
        pd, pg, ps = f"{name}#d", f"{name}#g", f"{name}#s"
        # bulk stays a direct rail node (mixed style, like real netlists)
        dev_lines.append(
            f"{name} {pd} {pg} {ps} {b} {MODEL[kind]} "
            f"L=3e-09 W=1.9e-08 AD=8.55e-16 AS=4.275e-16"
        )
        for net, pin in ((d, pd), (g, pg), (s, ps)):
            pins_by_net.setdefault(net, []).append(pin)

    # Stitch each net: parasitic R from an anchor through every pin in series.
    # Anchor = the port itself (if the net is a port) else two `netbase#k` nodes.
    r_lines: list[str] = []
    rc = 0
    for net in sorted(pins_by_net):
        pins = pins_by_net[net]
        if net in PORTS:
            chain = [net] + pins              # port is the named anchor
        else:
            chain = [f"{net}#1"] + pins + [f"{net}#2"]   # internal net anchors
        for a, c in zip(chain, chain[1:]):
            rc += 1
            r_lines.append(f"R{rc} {a} {c} 1.0")

    # A few parasitic C the engine MUST ignore for connectivity:
    #   pin-to-ground and one cross-net coupling cap.
    c_lines = [
        "CA1 XMLA0#g VSS 1.2e-18",
        "CA2 XSLA0#g VSS 1.1e-18",
        "CF1 XMLA0#g XSLA0#g 3.4e-19",   # coupling cap between master and slave gate
        "CA3 XOUT0#d VSS 2.0e-18",
    ]

    out = []
    out.append("* ===================================================================")
    out.append("* SDFX_LPE_PLACEHOLDER.subckt -- THROWAWAY synthetic scan DFF, LPE style.")
    out.append("* Format-faithful to the real SEGMENT 2 netlist (macro-subckt devices,")
    out.append("* private #d/#g/#s nodes, connectivity only via parasitic R, noise C).")
    out.append("* Generated by _gen_sdf_lpe.py -- do NOT hand-edit. No PDK; generic models.")
    out.append("* The engine must re-derive topology BLIND (R-merge + CCC), not by name.")
    out.append("* ===================================================================")
    out.append(f".subckt {CELL} {' '.join(PORTS)}")
    out.append("* --- transistors (macro subckts; terminals are private extracted nodes) ---")
    out.extend(dev_lines)
    out.append("* --- parasitic R (interconnect; all intra-net, contract for logical nets) ---")
    out.extend(r_lines)
    out.append("* --- parasitic C (to-ground / coupling; ignore for connectivity) ---")
    out.extend(c_lines)
    out.append(f".ends {CELL}")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    import os
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        f"{CELL}.subckt")
    with open(path, "w", encoding="ascii") as fh:
        fh.write(build())
    print(f"wrote {path}")
